baseURL: "https://ataullha.github.io/" 
title: Md. Ataullha
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This website hosts Moritz-Maria von Igelfeld's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Moritz-Maria von Igelfeld
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Md. Ataullha
          subtitle: "Hello! This is Md. Ataullha. I hold a B.Sc. in Computer Science and Engineering from Shahjalal University of Science and Technology (SUST) in Sylhet, Bangladesh. Currently, I am working as a full-time Lecturer in the Department of Computer Science and Engineering at Green University of Bangladesh in Dhaka. With a background in AI engineering, my research focuses on multilingual speech technologies and the development of accessible language tools for underrepresented communities—particularly those involving regional and low-resource languages. My academic interests include applied machine learning, large language model (LLM) evaluation, and exploring the intersection of ecological informatics with machine learning and speech technologies."
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Courses
              url: courses/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:ataullha00@gmail.com
        - name: Zoom
          url: https://us05web.zoom.us/j/3931734750?pwd=KNk8lpPMnr6lln1jbjXFTGSzDkuybS.1
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=N2dzzwsAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/ataullha
        - name: LinkedIn
          url: https://www.linkedin.com/in/ataullha/
        - name: ResearchGate
          url: https://www.researchgate.net/profile/Md-Ataullha-Saim
        - name: Facebook
          url: https://www.facebook.com/ataullha00

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Md. Ataullha"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2